on:
  push:
  pull_request:
  schedule:
    - cron: "0 7 * * *"

name: Test
jobs:
  Build:
    strategy:
      matrix:
        go-version: [ 1.19.X ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Test
        run: go test $(go list ./... | grep -v /benchmark | grep -v /runner) -covermode=atomic -coverprofile=coverprofile.out -short
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-umbrella
          file: coverprofile.out
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
